//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.12 at 11:53:20 PM IST 
//


package com.jh.vo.edi.x12.type810;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jh.vo.edi.x12.type810 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Sender_QNAME = new QName("", "sender");
    private final static QName _Receiver_QNAME = new QName("", "receiver");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jh.vo.edi.x12.type810
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressCT }
     * 
     */
    public AddressCT createAddressCT() {
        return new AddressCT();
    }

    /**
     * Create an instance of {@link Element }
     * 
     */
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link Interchange }
     * 
     */
    public Interchange createInterchange() {
        return new Interchange();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Transaction }
     * 
     */
    public Transaction createTransaction() {
        return new Transaction();
    }

    /**
     * Create an instance of {@link Loop }
     * 
     */
    public Loop createLoop() {
        return new Loop();
    }

    /**
     * Create an instance of {@link Segment }
     * 
     */
    public Segment createSegment() {
        return new Segment();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Ediroot810 }
     * 
     */
    public Ediroot810 createEdiroot810() {
        return new Ediroot810();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressCT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sender")
    public JAXBElement<AddressCT> createSender(AddressCT value) {
        return new JAXBElement<AddressCT>(_Sender_QNAME, AddressCT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressCT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "receiver")
    public JAXBElement<AddressCT> createReceiver(AddressCT value) {
        return new JAXBElement<AddressCT>(_Receiver_QNAME, AddressCT.class, null, value);
    }

}
