CREATE DATABASE `jh_etl` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */;

USE `jh_etl`;

CREATE TABLE `category` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(100) NOT NULL,
  `CODE` varchar(50) NOT NULL,
  `PARENT_ID` int(11) DEFAULT NULL,
  `SUPPLIER` varchar(20) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_CATEGORY_CODE` (`CODE`,`SUPPLIER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `product` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SKU` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `CATEGORY_ID` int(11) DEFAULT NULL,
  `TITLE` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `WIDTH` float DEFAULT NULL,
  `HEIGHT` float DEFAULT NULL,
  `LENGTH` float DEFAULT NULL,
  `WEIGHT` float DEFAULT NULL,
  `UPC` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `RETAIL_PRICE` double DEFAULT NULL,
  `RETAIL_UNIT` varchar(10) DEFAULT NULL,
  `IMAGE_LINK` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `SUPPLIER` varchar(10) NOT NULL,
  `DESCRIPTION` text,
  `CREATED_DATE` datetime NOT NULL,
  `MODIFIED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `SKU_UNIQUE` (`SKU`),
  KEY `SKU_SUPPLIER` (`SUPPLIER`,`SKU`),
  KEY `product_category_fk_idx` (`CATEGORY_ID`),
  CONSTRAINT `product_category_fk` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `category` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
